language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

env:
  - DATABASE_URI="dbname='politico' host='127.0.0.1' port='5432' user='admin' password='admin123'"
  

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE politico;" -U postgres
  - psql -c "CREATE OR REPLACE FUNCTION create_mytable ()
              RETURNS void AS
            $func$
            BEGIN
              IF EXISTS (SELECT 1 FROM pg_catalog.pg_tables 
                          WHERE  schemaname = 'politico') THEN
                  RAISE NOTICE 'Table politico already exists.';
              ELSE
                  CREATE TABLE politico;
              END IF;
            END
            $func$ LANGUAGE plpgsql;" -U postgres
            
  - psql -c "SELECT create_mytable(); ;" -U postgres
  
  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres


script:
    - coverage run --source=app/api -m pytest test && coverage report

after_success:
    - coveralls
