language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

env:
  - DATABASE_URL="dbname='politico' host='127.0.0.1' port='5432' user='postgres' password='postgres'"
  

services:
  - postgresql

before_script:
  - sudo -u postgres psql -c "CREATE DATABASE politico;" 
  - sudo export DATABASE_URL="dbname='politico' host='127.0.0.1' port='5432' user='postgres' password='postgres'"

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

script:
    - coverage run --source=app/api -m pytest test && coverage report

after_success:
    - coveralls
