language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

env:
  - DATABASE_URL="dbname='politico' host='127.0.0.1' port='5432' user='postgres' password='postgres'"
  

postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - "psql -c 'create database myapp_test;' -U postgres"
  - "rake db:migrate"

script:
    - coverage run --source=app/api -m pytest test && coverage report

after_success:
    - coveralls
