language: python
python:
    - "3.6"

install:
    - pip install -r requirements.txt

env:
  - DATABASE_URL="dbname='politico' user='postgres' host='localhost' password=''"
  

services:
  - postgresql

before_script:
  - sudo -u postgres psql -c "CREATE DATABASE politico;" 
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
  - DATABASE_URL="dbname='politico' user='postgres' host='localhost' password=''"

script:
    - coverage run --source=app/api -m pytest test && coverage report

after_success:
    - coveralls
